<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <LangVersion>latest</LangVersion>
    <PreBuildEvent>CALL cd "$(ProjectDir)"
if $(ConfigurationName) == Debug npm run build
if $(ConfigurationName) == Release npm run buildrelease
</PreBuildEvent>
    <TargetFramework>net9.0</TargetFramework>
    <OutputPath>bin\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>
  <ItemGroup>
    <None Include="wwwroot\Content\bootstrap4-datetimepicker.css" />
    <None Include="wwwroot\Images\2-Line - 500.png" />
    <None Include="wwwroot\Images\openSEE - Waveform Viewer Header.png" />
    <None Include="wwwroot\Images\openSEE.jpg" />
    <None Include="wwwroot\Images\openSEELogo.png" />
    <Content Include="Shared\Content\Images\ui-icons_444444_256x240.png" />
    <Content Include="Shared\Content\Images\ui-icons_555555_256x240.png" />
    <Content Include="Shared\Content\Images\ui-icons_777620_256x240.png" />
    <Content Include="Shared\Content\Images\ui-icons_777777_256x240.png" />
    <Content Include="Shared\Content\Images\ui-icons_cc0000_256x240.png" />
    <Content Include="Shared\Scripts\default.ployfill.js" />
    <PackageReference Include="Gemstone.Web" Version="1.0.161" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.2" />
  </ItemGroup>
  <ItemGroup>
    <None Include="package.json" />
    <None Include="tsconfig.json" />
    <None Include="wwwroot\Scripts\OpenSee.js" />
    <None Include="wwwroot\Scripts\TSX\Components\About.tsx" />
    <None Include="wwwroot\Scripts\TSX\Components\AnalyticOptions.tsx" />
    <None Include="wwwroot\Scripts\TSX\Components\Menu.tsx" />
    <None Include="wwwroot\Scripts\TSX\Components\OpenSEENavbar.tsx" />
    <None Include="wwwroot\Scripts\TSX\Components\OverlappingEvents.tsx" />
    <None Include="wwwroot\Scripts\TSX\Context\HoverContext.tsx" />
    <None Include="wwwroot\Scripts\TSX\Context\HoverProvider.tsx" />
    <None Include="wwwroot\Scripts\TSX\defaults.ts" />
    <None Include="wwwroot\Scripts\TSX\global.d.ts" />
    <None Include="wwwroot\Scripts\TSX\Graphs\BarChartBase.tsx" />
    <None Include="wwwroot\Scripts\TSX\Graphs\ChartIcons.tsx" />
    <None Include="wwwroot\Scripts\TSX\Graphs\LegendBase.tsx" />
    <None Include="wwwroot\Scripts\TSX\Graphs\LineChartBase.tsx" />
    <None Include="wwwroot\Scripts\TSX\Graphs\Utilities.tsx" />
    <None Include="wwwroot\Scripts\TSX\hooks.ts" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\AccumulatedPoints.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\EventInfo.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\FFTTable.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\HarmonicStats.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\LightningData.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\PhasorChart.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\ScalarStats.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\SettingWindow.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\FaultSpecificsModal.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\TimeCorrelatedSags.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\Tooltip.tsx" />
    <None Include="wwwroot\Scripts\TSX\jQueryUI Widgets\TooltipWithDelta.tsx" />
    <None Include="wwwroot\Scripts\TSX\openSEE.tsx" />
    <None Include="wwwroot\Scripts\TSX\store\analyticSlice.tsx" />
    <None Include="wwwroot\Scripts\TSX\store\dataSlice.tsx" />
    <None Include="wwwroot\Scripts\TSX\store\GraphLogic.tsx" />
    <None Include="wwwroot\Scripts\TSX\store\overlappingEventsSlice.tsx" />
    <None Include="wwwroot\Scripts\TSX\store\queryThunk.tsx" />
    <None Include="wwwroot\Scripts\TSX\store\RequestHandler.tsx" />
    <None Include="wwwroot\Scripts\TSX\store\settingSlice.tsx" />
    <None Include="wwwroot\Scripts\TSX\store\store.tsx" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{4A0DDDB5-7A95-4FBF-97CC-616D07737A77}" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MathNet.Numerics, Version=5.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\Dependencies\NuGet\MathNet.Numerics.5.0.0-alpha02\lib\net48\MathNet.Numerics.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Libraries\FaultAlgorithms\FaultAlgorithms.csproj" />
    <ProjectReference Include="..\Libraries\FaultData\FaultData.csproj" />
    <ProjectReference Include="..\Libraries\openXDA.Model\openXDA.Model.csproj" />
    <ProjectReference Include="..\Libraries\PQDS\PQDS.csproj" />
  </ItemGroup>
  <ItemGroup>
    <TypeScriptCompile Include="wwwroot\Scripts\TSX\Context\HoverContext.tsx" />
    <TypeScriptCompile Include="wwwroot\Scripts\TSX\Context\HoverProvider.tsx" />
    <TypeScriptCompile Include="wwwroot\Scripts\TSX\jQueryUI Widgets\EventInfo.tsx" />
  </ItemGroup>
</Project>