<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Configurations>Debug;Development;Release</Configurations>
    <OutputType>Library</OutputType>
    <AssemblyTitle>PQDS</AssemblyTitle>
    <Product>PQDS</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <AssemblyVersion>3.0.5.69</AssemblyVersion>
    <FileVersion>3.0.5.69</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\..\Build\Output\Debug\Libraries\</OutputPath>
    <DocumentationFile>..\..\..\Build\Output\Debug\Libraries\PQDS.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\..\..\Build\Output\Release\Libraries\</OutputPath>
    <DocumentationFile>..\..\..\Build\Output\Release\Libraries\PQDS.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>