param(
    [Parameter(Mandatory)]
    [string]$GithubToken,
    [string]$DevelopmentBranchName = "development"
)

$headers = @{
    Authorization = "token $GithubToken"
    Accept = "application/vnd.github.v3+json"
}

function Get-AheadCount {
    param(
        [string]$Repository,
        [string]$MainBranch
    )

    $developmentUrl = "https://api.github.com/repos/$Repository/branches/development"

    try {
        Invoke-RestMethod -Uri $developmentUrl -Headers $headers -Method Get -ErrorAction Stop | Out-Null
    }
    catch {
        $mainReference = Invoke-RestMethod `
            -Uri "https://api.github.com/repos/$Repository/git/ref/heads/$MainBranch" `
            -Headers $headers `
            -Method Get
        $body = @{
            ref = "refs/heads/development"
            sha = $mainReference.object.sha
        } | ConvertTo-Json

        Invoke-RestMethod `
            -Uri "https://api.github.com/repos/$Repository/git/refs" `
            -Headers $headers `
            -Method Post `
            -Body $body `
            -ContentType "application/json" | Out-Null

        return 0
    }

    $comparison = Invoke-RestMethod `
        -Uri "https://api.github.com/repos/$Repository/compare/$MainBranch...development" `
        -Headers $headers `
        -Method Get

    return $comparison.ahead_by
}

function New-ReleasePullRequest {
    param(
        [string]$Repository,
        [string]$MainBranch,
        [string]$Organization
    )

    $existingUrl = "https://api.github.com/repos/$Repository/pulls?state=open&head=${Organization}:development&base=$MainBranch"
    $existingPulls = Invoke-RestMethod -Uri $existingUrl -Headers $headers -Method Get

    if ($existingPulls.Count -gt 0) {
        return $existingPulls[0].html_url
    }

    $body = @{
        title = "Release Update"
        head = "development"
        base = $MainBranch
        body = "This pull request was generated by an openSEE release."
    } | ConvertTo-Json

    $response = Invoke-RestMethod `
        -Uri "https://api.github.com/repos/$Repository/pulls" `
        -Headers $headers `
        -Method Post `
        -Body $body `
        -ContentType "application/json"

    return $response.html_url
}

$repositoryList = Invoke-WebRequest `
    -Uri "https://raw.githubusercontent.com/gemstone/root-dev/refs/heads/master/repos.txt" `
    -UseBasicParsing |
    Select-Object -ExpandProperty Content

$repositories = $repositoryList -split "`n" |
    Where-Object { -not $_.Trim().StartsWith("::") } |
    ForEach-Object { $_.Trim().Split('/')[0].Trim() } |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
    Sort-Object -Unique

$pullRequests = @()

foreach ($repositoryName in $repositories) {
    $repository = "Gemstone/$repositoryName"

    if ((Get-AheadCount -Repository $repository -MainBranch "master") -gt 0) {
        $pullRequests += New-ReleasePullRequest `
            -Repository $repository `
            -MainBranch "master" `
            -Organization "Gemstone"
    }
}

if ($pullRequests.Count -eq 0) {
    return
}

$comment = "The following dependency release pull requests were generated:`n"
foreach ($pullRequest in $pullRequests) {
    $comment += "- [ ] $pullRequest`n"
}

& "$PSScriptRoot\GithubComment.ps1" `
    -Comment $comment `
    -BranchName $DevelopmentBranchName `
    -GithubToken $GithubToken `
    -RepoOwner "GridProtectionAlliance" `
    -RepoName "openSEE"
