param(
    [string]$GithubToken,
    [string]$DevelopmentBranchName = "development"
)

$headers = @{
    "Authorization" = "token $GithubToken"
    "Accept" = "application/vnd.github.v3+json"
}

#Count Changes in Dev vs Master
function CountChanges {
    param(
        [string]$Repository,
        [string]$mainBranch
    )

    # Check if Development Branch exists
    $branchURL = "https://api.github.com/repos/$Repository/branches/development"

    Write-Host "Checking for development branch in $branchURL"

    try {
        $prs = Invoke-RestMethod -Uri $branchURL -Headers $headers -Method Get -ErrorAction Stop
    }
    catch {
        # Generate a development Branch on top of main if it doesn't exist
        $refUrl = "https://api.github.com/repos/$Repository/git/ref/heads/$mainBranch"

        $baseRef = Invoke-RestMethod -Uri $refUrl -Headers $headers -Method Get
        $baseSha = $baseRef.object.sha

        $body = @{
            ref = "refs/heads/development"
            sha = $baseSha
        } | ConvertTo-Json

        $newRefUrl = "https://api.github.com/repos/$Repository/git/refs"
        
        Invoke-RestMethod -Uri $newRefUrl `
                        -Headers $headers `
                        -Method Post `
                        -Body $body `
                        -ContentType "application/json"
                        
        Write-Host "No development branch found for $Repository. Generated development branch based on $mainBranch"
        return 0;
    }
        
    
    $branchURL = "https://api.github.com/repos/$Repository/compare/$mainBranch...development"
    Write-Host "Checking for diff branch in $branchURL"

    $prs = Invoke-RestMethod -Uri $branchURL -Headers $headers -Method Get

    return $prs.ahead_by
}

function GeneratePR {
    param(
        [string]$Repository,
        [string]$Title,
        [string]$Body,
        [string]$mainBranch,
        [string]$organization
    )

   # Check if PR already exists
    $url = "https://api.github.com/repos/$Repository/pulls?state=open&head=${organization}:development&base=$mainBranch"
    $prs = Invoke-RestMethod -Uri $url -Headers $headers -Method Get

    if ($prs.Count -gt 0) {
        Write-Host "PR Already exists"
        return $prs[0].html_url
    }
   
    $url = "https://api.github.com/repos/$Repository/pulls"

    $body = @{
        title = "$Title"
        head  = "development"
        base  = "$mainBranch"
        body  = "$Body"
    } | ConvertTo-Json

    $response = Invoke-RestMethod -Uri $url `
        -Headers $headers `
        -Method Post `
        -Body $body `
        -ContentType "application/json" `

    return $response.html_url
    
}

# Get all Gemstone Repos
$repoFileURL = "https://raw.githubusercontent.com/gemstone/root-dev/refs/heads/master/repos.txt"
$gemstoneRepos = Invoke-WebRequest -Uri $repoFileURL -UseBasicParsing | Select-Object -ExpandProperty Content
$gemstoneRepos = $gemstoneRepos -split "`n" | Where-Object { -not $_.Trim().StartsWith("::") }

# Separate repos names from project names
for ($i = 0; $i -lt $gemstoneRepos.Length; $i++){
    $parts = $gemstoneRepos[$i].Trim().Split('/');

    if ($parts.Length -eq 2) {
        $gemstoneRepos[$i] = $parts[0].Trim()
    }
    else {
        $gemstoneRepos[$i] = ""
    }
}

$gemstoneRepos = $gemstoneRepos | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }

$prs = @()

foreach ($repo in $gemstoneRepos) {
    $changes = CountChanges -Repository "Gemstone/$repo" -mainBranch "master"
    if ($changes -gt 0) {
        Write-Host "There are $changes changes in $repo."
        $prLink = GeneratePR -Repository "Gemstone/$repo" -Title "Release Update" -Body "This PR was Generated by a release of openSEE" -mainBranch "master" -organization "Gemstone"
        $prs += $prLink
    }
}

# Add Comments to the PR with the Open PRs in the openSEE Repo
if ($prs.Count -gt 0) {
    $commentBody = "The following PRs have been generated for the dependencies: `n"
    foreach ($pr in $prs) {
        $commentBody += "- [ ] $pr `n"
    }

& "$PSScriptRoot\GithubComment.ps1" -Comment $commentBody -BranchName "$DevelopmentBranchName" -GithubToken $GithubToken -RepoOwner "GridProtectionAlliance" -RepoName "openSEE"

}
